ALTER TABLE security_events
    DROP CONSTRAINT security_events_event_type_check,
    ADD CONSTRAINT security_events_event_type_check
        CHECK (event_type IN (
            'account_registered',
            'login_succeeded',
            'login_failed',
            'account_locked',
            'account_unlocked',
            'profile_updated',
            'password_changed',
            'password_reset_requested',
            'password_reset_completed',
            'refresh_token_reused',
            'session_revoked',
            'all_sessions_revoked',
            'logout',
            'mfa_setup_started',
            'mfa_enabled',
            'mfa_disabled',
            'mfa_recovery_codes_regenerated',
            'mfa_login_failed',
            'email_verification_requested',
            'email_verified',
            'user_role_changed',
            'user_status_changed',
            'member_invitation_sent',
            'member_invitation_revoked',
            'member_invitation_accepted',
            'admin_audit_exported'
        ));
